server:
  port: 8008
spring:
  application:
    name: study-consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}