server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3333/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: springmvc
    password: abcd1234
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
#    cluster:
#      nodes:
#        - 192.168.6.139:6391
#        - 192.168.6.139:6392
#        - 192.168.6.139:6393
#        - 192.168.6.139:6394
#        - 192.168.6.139:6395
#        - 192.168.6.139:6396

mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  - classpath*:com/**/mapper/*.xml